spring:
  cloud:
    gateway:
      routes:
        - id: test_routes
          uri: http://www.baidu.com
          predicates:
            - Query=url,wb

        - id: qq_routes
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

        ## 精确等级高的路由放在前面
        - id: product_route
          uri: lb://store-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

